# project config
spring.application.name=jpaboard

# 세션값 사용하기 위해 추가
spring.mustache.servlet.expose-session-attributes = true

# server config
server.servlet.context-path=/
server.port=8080

# DB config
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3307/jpa
spring.datasource.username=root
spring.datasource.password=java1234

# jpa config
# spring.jpa.show-sql=true
# 쿼리 줄바꿈 적용
spring.jpa.properties.hibernate.format_sql=true

# log config
logging.level.com.example.jpaboard.repository=debug
logging.level.com.example.jpaboard.controller=debug
# 디버그 레벨로 쿼리 출력
logging.level.org.hibernate.SQL=debug
# 매개변수 값 보여주기
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE