spring.application.name=jpa2
# 세션값 사용하기 위해 추가
spring.mustache.servlet.expose-session-attributes = true

# server config
server.servlet.context-path=/
server.port=8080

# DB config
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3307/jpa2
spring.datasource.username=root
spring.datasource.password=java1234

# jpa config
# spring.jpa.show-sql=true
# 쿼리 줄바꿈 적용
spring.jpa.properties.hibernate.format_sql=true